name: Docs

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install documentation dependencies
        run: pip install -e ".[docs]"

      - name: Build documentation
        run: |
          cd docs
          make html